#pragma once

#include "OBJ_Loader.h"
class PackageTool
{
private:
	struct PackagedTexture
	{
		uint32_t width, height;
		uint32_t rowPitch;
		BYTE* data;
	};

public:
	struct PackageHeader
	{
		char id[3]; // PCK or PKG or whatever, not strictly necessary but feels official
		uint8_t assetCount;
		uint32_t size;
	};

	struct ChunkHeader
	{
		char type[4];				// Ex: TEX, MESH, AUD ...
		uint32_t chunkSize;			// Chunk header not included
		GUID guid;					// Generated by hashing the compressed data.
		uint64_t readableSize;
		// Here follows a zero-terminated string that is the humanreadble name. Read as you deem fit
	};

	struct TextureHeader
	{
		char textureType[4]; // COL, NORM, SPEC ...
		uint32_t dataSize;
		uint32_t width, height;
		uint32_t rowPitch;
	};

	struct MeshHeader
	{
		std::string materialName;
		uint32_t verticesDataSize; //The size of the vertexdata part of the data.
		uint32_t indicesDataSize; //The size of the indexdata part of the data.
	};
	
	struct MaterialHeader
	{
		uint32_t dataSize;
	};
private:
public:
	PackageTool() = default;
	~PackageTool() = default;

	static std::string Package(const std::string& dirPath);
private:
	static PackagedTexture PackageTexture(const std::string& texPath);
};

