#pragma once
class PackageTool
{
private:
	struct PackagedTexture
	{
		uint32_t width, height;
		uint32_t rowPitch;
		std::vector<BYTE> dataVec;
	};

public:
	struct PackageHeader
	{
		char id[3]; // PCK or PKG or whatever, not strictly necessary but feels official
		uint8_t assetCount;
		uint32_t size;
	};

	struct ChunkHeader
	{
		char type[4];				// Ex: TEX, MESH, AUD ...
		uint32_t chunkSize;			// Chunk header not included
		GUID guid;					// Generated by hashing the compressed data.
		uint64_t readableSize;
		// Here follows a non-zero-terminated string that is the humanreadble name. Read as you deem fit
	};

	struct TextureHeader
	{
		char textureType[4]; // COL, NORM, SPEC ...
		uint32_t dataSize;
		uint32_t width, height;
		uint32_t rowPitch;
	};

	struct MeshHeader
	{
		const char* meshName;
		const char* materialName;	//The material the mesh uses.
		uint64_t verticesDataSize;	//The size of the vertexdata part of the data.
		uint64_t indicesDataSize;	//The size of the indexdata part of the data.
	};
	
	struct MaterialHeader
	{
		const char* materialName;
		uint32_t dataSize;
	};
private:
public:
	PackageTool() = default;
	~PackageTool() = default;

	static std::string Package(const char* dirPath);
private:
	static PackagedTexture PackageTexture(const std::string& texPath);
	static void PadTexture(PackagedTexture& tex, const BYTE* imgData, int channels);
};

